from enum import Enum, IntEnum

class DiagnosticLayerEnum(IntEnum):
    DEFAULT_SESSION = 1
    S3_CLIENT_TIME_INIT = 2000
    S3_SERVER_TIME_INIT = 5000
    P2_SERVER_INIT = 50
    P2_EXTENDED_SERVER_INIT = 5000
    REPEAT_REQUEST_AFTER_INIT = 200

class DiagnosticsNRC(IntEnum):
    SERVICE_NOT_SUPPORTED = 0x11
    SUB_FUNCTION_NOT_SUPPORTED = 0x12
    INVALID_MESSAGE_LENGTH = 0x13
    CONDITIONS_NOT_CORRECT = 0x22
    REQUEST_SEQUENCE_ERROR = 0x24
    REQUEST_OUT_OF_RANGE = 0x31
    SECURITY_ACCESS_DENIED = 0x33
    INVALID_KEY = 0x35
    EXCEEDED_NUMBER_OF_ATTEMPTS = 0x36
    REQUIRED_TIME_DELAY_HAS_NOT_EXPIRED = 0x37
    SUB_FUNCTION_NOT_SUPPORTED_IN_THE_ACTIVE_SESSION = 0x7E
    SERVICE_NOT_SUPPORTED_IN_THE_ACTIVE_SESSION = 0x7F

class DiagnosticSessionStatus:
    ACTIVE_SESSION = 1
    SESSION_TIME_OUT = False
    ROUTING_ACTIVATION_DONE = False
    POWER_MODE_STATUS = False

class DiagnosticServices(IntEnum):
    POSITIVE_RESPONSE_CODE = 0x40
    SESSION = 0x10
    ECU_RESET = 0x11
    ROUTINE_CONTROL = 0x31
    DTC = 0x19
    READ_DATA_BY_IDENTIFIER = 0x22
    WRITE_DATA_BY_IDENTIFIER = 0x2E
    SECURITY_ACCESS = 0x27








