CheckMemoryRoutine:
  session: [!!int 0x02]
  security_service: 0x11
    
OnDemandSelfTestRoutine:
  session: [!!int 0x01, !!int 0x03]
  security_service: 0
    
ProgrammingPreconditionsRoutine:
  session: [!!int 0x03]
  security_service: 0
    
CheckUploadPreconditionRoutine:
  session: [!!int 0x03]
  security_service: 0x11
    
CompleteAndCompatibilityCheckRoutine:
  session: [!!int 0x02]
  security_service: 0x11