
ActiveDiagnosticSession:
  session: [!!int 0x01, !!int 0x02, !!int 0x03]
  security_service: 0

VehicleManufacturerSparePartNumber:
  session: [!!int 0x02]
  security_service: 1

VehicleManufacturerEcuSoftwareVersionNumber:
  session: [!!int 0x02]
  security_service: 1

VehicleManufacturerECUHardWareNumber:
  session: [!!int 0x02, !!int 0x03]
  security_service: 1

SystemNameOrEngineType:
  session: [!!int 0x02, !!int 0x03]
  security_service: 0

VehicleIdentificationNumber:
  session: [!!int 0x01, !!int 0x02, !!int 0x03]
  security_service: 0

### write data by identifiers

GlobalRealTime:
  session: [!!int 0x01, !!int 0x02, !!int 0x03]
  security_service: 0x11

TotalDistance:
  session: [!!int 0x03]
  security_service: 0x11

VehicleBatteryVoltage:
  session: [!!int 0x03]
  security_service: 0x11

UsageMode:
  session: [!!int 0x01, !!int 0x02, !!int 0x03]
  security_service: 0x11

ElectricPowerLevel:
  session: [!!int 0x03]
  security_service: 0x11
